### ISSUE TITLE
Allow setting None to NestedModel field

### ISSUE THREAD

**Issue by lwiecek** [octabytes/FireO#101]
Hi,

I'm setting up my models like this

```python3
from fireo import models
class NestedModel(models.Model):
     a = models.TextField()

class TestingTheModel(models.Model):
     nested = models.NestedModel(NestedModel, required=False, default=None)
     b = models.TextField()
     class Meta:
             ignore_none_field = True
```

and then saving the model:

```python3
TestingTheModel(nested=None, b='xd').save()
```

The Firestore document after this operation:
```
{
   "nested": {},
   "b": "xd"
}
```

I would like to get this data in Firestore:
```
{
   "nested": None,
   "b": "xd"
}
```

Any tips on how this could be achieved?

I am more than happy to have any solution to his problem: adding parameters, CustomField, extending NestedModel etc. works for me.

**Comment by AxeemHaider** [comment]
I think this problem is because FireO create empty `dict` for nested model for direct assignment. Here is the [code](https://github.com/octabytes/FireO/blob/master/src/fireo/models/model.py#L138)
[parese_field](https://github.com/octabytes/FireO/blob/master/src/fireo/queries/create_query.py#L75) is method which get values from model before setting to firestore. You have to check if `dict` is not empty currently i'm only checking if the field value is not `None` [code](https://github.com/octabytes/FireO/blob/master/src/fireo/queries/create_query.py#L98)

If you can fix it create a pull request

**Comment by monthero** [comment]
I wrote this "flexible" NestedModelField that has been working quite well for me, allows for repeated nested model as well. Saves things as None, Dict or List[Dict]

```python
class FlexibleNestedModelField(Field):
    allowed_attributes = ["repeated"]
    repeated: bool = False
    required: bool = False

    def __init__(self, model, *args, **kwargs):
        if "required" not in kwargs:
            kwargs["required"] = False

        if 'repeated' not in kwargs:
            kwargs['repeated'] = False

        self.required = kwargs['required']
        super().__init__(*args, **kwargs)
        self.repeated = kwargs['repeated']
        # Check nested model class is subclass for Model
        from fireo.models import Model

        if not issubclass(model, Model):
            raise NestedModelTypeError(
                f'Nested model "{model.__name__}" must be inherit from Model '
                f'class')
        self.nested_model = model

    def attr_repeated(self, attr_val, field_val):
        """Method for attribute auto_add"""
        if attr_val:
            if not field_val:
                return []
            if field_val and not isinstance(field_val, list):
                return [field_val]
        return field_val

    def db_value(self, val):
        if isinstance(val, list) and not self.repeated:
            raise ValueError(
                "Got list but 'repeated' is set to False"
            )

        if val is None and self.required:
            if self.repeated:
                return []
            else:
                raise ValueError(
                    "Value cannot be empty when 'required' is True"
                )

        if val:
            return (
                [entry.to_dict() for entry in val]
                if isinstance(val, list)
                else val.to_dict()
            )

        return val
```

**Comment by stvnksslr** [comment]
would we be able to get this model merged into the library itself? its super useful when working with existing datasets that might be a mess and giving leeway to port over.

**Comment by AxeemHaider** [comment]
@monthero Thanks for your effort for creating this `FlexibleNestedModelField` it will be great if you send a PR for this I will merge it. Name it properly instead of `FlexibleNestedModelField` and if you can write docs for how to use it will be helpful for other.

[Fireo Docs](https://github.com/octabytes/FireO/tree/gh-pages)

**Comment by Arlan2191** [comment]
just a suggestion, maybe you can name it ListNestedModelField

**Comment by AxeemHaider** [comment]
I think it will be great if `ExtendedNestedModel`
