### ISSUE TITLE
Dynamic Column Names

### ISSUE THREAD

**Issue by stvnksslr** [octabytes/FireO#114]
I have an issue where with a very large existing data set where they are using id's as the field name for a given collection.

So when trying to map the data to a class Im trying to figure out how to do something akin to

collection looks like this with each element in the collection having there guid be the name of the mapfield name
```
cats/<guid>
cats/<guid>
```

```python
class Cats(models.model):
  cat_info = MapField(column_name=<some_guid>)
```
where _id is the id for the parent document so that when you query or save you can use the type field within the class.

I think there might be a way to do this via extending the custom field class but im at a loss how to do it currently.

**Comment by AxeemHaider** [comment]
When you get any document using **FireO** parent key is already attached with it you don't have to remember it manually. 
You can check example here [Creating Subcollection](https://octabyte.io/FireO/managing-data/adding-data/#sub-collection)

If you want to reference another document from the document you can use [Reference Field](https://octabyte.io/FireO/fields/reference-field/)

If you just want to save the parent id or key for some reason then you can simply save it as [TextField](https://octabyte.io/FireO/fields/text-field/) because `ids` in **Firestore** are `strings`.

If you want to manually generate id for document you can use [IDField](https://octabyte.io/FireO/fields/id-field/)

Its better to look documentation before using Fireo. [FireO docs](https://octabyte.io/FireO/)

**Comment by stvnksslr** [comment]
Sorry I may have explained it incorrectly, what i mean is that the existing data in the firestore is a guid representing a key as a map its a bad data structure but I cant seem to understand a way to model it.

how would you create a data model where the column name is a guid like i have in the example above.

**Comment by AxeemHaider** [comment]
I think there is no way to change the column name dynamically.

**Comment by stvnksslr** [comment]
ah ok I kinda figured that it was a long shot, I really appreciate the time to look into this.
