### ISSUE TITLE
fireo.queries.errors.InvalidKey

### ISSUE THREAD

**Issue by em1le** [octabytes/FireO#152]
Good day,

First, I want to thank you for providing such ORM for firebase, you've made a great work.

Recently i was trying to retrieve a single document from collection as follow : 

```python
entity_key = "IAxjICnsb5qEw4ZOkavE"
Entity.collections.get(entity_key)
```

And it raised the following exception : 
`fireo.queries.errors.InvalidKey: Invalid key is given, expected "Entity" type key, got "" type key`

Here is my model : 
_models.py :_
```python
from fireo.fields import BooleanField
from fireo.models import Model
class Entity(Model):
    active = BooleanField(default=True)
```

Below you find how i simply created my model and a screenshot of my document in firebase : 

<img width="777" alt="Capture d’écran 2022-03-12 à 19 12 18" src="https://user-images.githubusercontent.com/22121480/158029770-641da7c6-c316-4e11-88f7-b01616efabd3.png">

What do i do wrong to encounter such exception ?

**Comment by AxeemHaider** [comment]
Actually firebase key contains the collection name also something like `entity/IAxjICnsb5qEw4ZOkavE` currently fireo not able to get by `id` because it is very difficult to work with deep nested documents but there is a util that generate key from id [Generate key from Id](https://octabyte.io/FireO/utils/#key-from-id-and-model)

Whenever you create the document, created doc contains the `key` which you can use later for getting document or reference.
Check the basic [Quick start](https://octabyte.io/FireO/quick-start/) to see how FireO work.

If you still have any query please let me know. 

Happy coding!
