### ISSUE TITLE
Can I perform an upsert?

### ISSUE THREAD

**Issue by jonesnc** [octabytes/FireO#37]
Is it possible to perform an upsert with `fireo`, and if so, could you provide a quick example of how to do so?

**Comment by AxeemHaider** [comment]
What do you mean by **upsert** ? If you mean is to add data if not exist and **override** data if already exist then it is possible. You can simple save the data with `id` if `id` match to any existing document then it will update otherwise it create the new one.

If you mean is to add data if not exist and **update** data if already exist then there is no direct function for this but you can check first if document exist then update otherwise create new one.

```python
u = User.collection.get('id-123')
if u:
 # update document
else:
 # create document
```

*Collaborate: create `upsert` method and send pull request*

**Comment by jonesnc** [comment]
Thanks for the response!

I'm looking for the first method, to override data if it already exists, but I also want to make sure that I'm only making one request when I perform the upsert.

**Comment by jonesnc** [comment]
Alright, I tried your suggestion of setting the `id` before saving, and I'm running into an issue. The `id` doesn't appear to be getting set to what I provide, it's only using the randomly-generated ID that firestore provides.

Here's my code. What am I doing wrong?

```python
class Tweet(Model):
    tweet = TextField(

t = Tweet.collection.get('tweets2/123')
new_tweet = Tweet()
new_tweet.tweet = 'sdfjkl'
new_tweet.id = '123'
new_tweet.save()
print(new_tweet.key)
```

**Comment by jonesnc** [comment]
I figured it out!

In order for the `id` to be set when I create a new `Tweet` document, I have to change my `Tweet` model to look like this:

class Tweet(Model):
    id = IDField()
    tweet = TextField()

    class Meta:
        collection_name = 'tweets'

**Comment by jonesnc** [comment]
I'm not sure an `upsert` method is required, since the `save()` method effectively performs an upsert.

**Comment by AxeemHaider** [comment]
`save()` method work as `upsert` when first you are getting data and then update any field and `save` it will work as `upsert` otherwise if you provide same `id` with any other document then it will **override** the document. 

```python
class Tweet(Model):
    id = IDField()
    tweet = TextField()
    other_field = TextField()


t = Tweet()
t.id = 'id-123'
t.tweet = 'some tweet'
t.other_field = 'any value'
t.save()

# When save() method behave like upsert
t2 = Tweet.collection.get(t.key)
t2.tweet = 'tweet changed'
t2.save()

# When save() method behave like override
# In this case other_field will be None
t3 = Tweet()
t3.id = 'id-123'
t3.tweet = 'tweet changed'
t3.save()
```

Actually `save()` always **override** the document but when you first `get()` the document change any field and save it other fields are already containing the values so it look like `upsert()` method.
if you `print(t2)` you will see the value of `t2.other_field` 

```python
t2 = Tweet.collection.get(t.key)
print(t2)
t2.tweet = 'tweet changed'
t2.save()

# This work same as
t2 = Tweet()
t2.id = 'id-123'
t2.tweet = 'some tweet'
t2.other_field = 'any value'
t2.save()
```
