### ISSUE TITLE
Reference Field - Failed to save after instance created

### ISSUE THREAD

**Issue by weiztech** [octabytes/FireO#82]
```
class User(Model):
    name = TextField(required=True)


class UserActivity(Model):
    user = ReferenceField(User, auto_load=False)


# this is working
activity = UserActivity.collection.save(user=user)

# it will trigger below error on save
activity.save()

ReferenceTypeError: Invalid reference type. Field "user" required value type "User", but got "ReferenceDocLoader
```

the same error also happened on `get` then `save` UserActivity

**Comment by AxeemHaider** [comment]
Because you are doing it wrong. `collection.save()` method is supposed to use **internally** there is no `save()` method for public use. There is save method in **instance** level. There is `collection.create()` if you want to use. 

Check documentation for [Adding data](https://octabyte.io/FireO/managing-data/adding-data/)
Also [Adding data using Managaer](https://octabyte.io/FireO/managing-data/adding-data/#using-manager)

**Comment by weiztech** [comment]
Hi @AxeemHaider , 
sorry, I have did typo and fix it above.
so on add new , I did use `create` method not `save`.

current issue tested with `fireo==1.3.8`

**Comment by AxeemHaider** [comment]
Why you want to `save` after **creating** document you don't need to `save` it. 

The reason why it is not saving is as mention in error message itself.
`ReferenceTypeError: Invalid reference type. Field "user" required value type "User", but got "ReferenceDocLoader`

Because you set `auto_load=False` that's why when you try to save it error come up **invalid type** because it require `User` type. set `auto_load=True` so it load the `User` document or load it before saving it. 

```python
activity = UserActivity.collection.create(user=user)
activity.user = activity.user.get()
activity.save()
```

**Comment by weiztech** [comment]
About the creating document and save it, this is just sample to reproduce the issue.

```
class ReferenceTestModel):
    Ref1 = ReferenceField(Amodel, auto_load=False)
    Ref2= ReferenceField(XModel, auto_load=False)
    Ref3= ReferenceField(YModel, auto_load=False)
    text = TextField(required=True)
```

hmm so,  if I have above model instance and want to change **only** one field: `text`.
Did you mean, need to load `all available reference fields ` for save method to work ?

**Comment by AxeemHaider** [comment]
You have to use `update()` method. Check Documentation for [Update](https://octabyte.io/FireO/querying-data/updating-data/)
