### ISSUE TITLE
Batch with manager create returns None.

### ISSUE THREAD

**Issue by ynishi** [octabytes/FireO#94]
Hi there!
I tried to batch as document below, but current manager's create with batch returned None in my case.
Is there way to work manager with batch for change value of object after create? If the behavior is right, remove update part.

https://github.com/octabytes/FireO/blob/gh-pages/managing-data/transaction-and-batches.md#batched-writes
https://github.com/octabytes/FireO/commit/1a6e0bc21c1bb7ce2137f6a872a20e5d8151ca5d
```
city = City.collection.create(batch=batch, state='NYC', population=500000)
# Update the population for SF
city.population = 1000000
city.update(batch=batch)
```

tried with ver 1.4.1
https://github.com/octabytes/FireO/blob/v1.4.1/src/fireo/managers/managers.py#L153
```
batch = fireo.batch()
user_batch = User.collection.create(name="Name1", batch=batch)
print(user_batch)

> None
```

**Comment by AxeemHaider** [comment]
Hi thanks for pointing this out this is just typing mistake. 

It does not return anything because these are write operations as it says **Batched writes** it is not limitation from `FireO` but from `Cloud Firestore`. Side note batches operate only when you hit `commit()`

But yes you can **UPDATE** documents with batches as well.

**Comment by ynishi** [comment]
Thanks so match!
I understand Firestore's limitation, also read Firestore's document.
