### ISSUE TITLE
How the tests are organized? 

### ISSUE THREAD

**Issue by AIGeneratedUsername** [octabytes/FireO#99]
Maybe I would like to use the library in the future and contribute to it, but I do not understand how your tests are organized.

The "FireO/src/tests/" folder contains a lot of folders named like "v_xxx".

- What that versioning means? Does this project's architecture have a specific name so I can read about it somewhere?

- How to understand where to put a new test?

Thank you for your time in advance.

**Comment by AxeemHaider** [comment]
When we started this Lib we put all the tests under `FireO/src/tests/` folder but as tests are grow it's hard to find the specific test. So we decide to create separate folder for each version. For example for version `v 1.1.8` there is folder `tests/v118` But later we decide not to create separate for minor version. For example for version `v 1.2.0 to v 1.2....` only create one folder `tests/v12` all tests related to this version will go into this folder. 

Only purpose to creating new folder for versions is to easily finding tests and which bugs and issues are fixed in which version.  If you have any better idea please let us know. 

Thanks!

**Comment by AIGeneratedUsername** [comment]
Thank you for the information.
